DROP DATABASE IF EXISTS TESTEWEB2;

--
-- Create schema TESTEWEB2
--

CREATE DATABASE IF NOT EXISTS TESTEWEB2;
USE TESTEWEB2;

--
-- Definition of table TB_MOTORISTA
--

DROP TABLE IF EXISTS TB_MOTORISTA;
CREATE TABLE TB_MOTORISTA(
	ID_MOT				INTEGER			    AUTO_INCREMENT,
    NOME_MOT			VARCHAR(50)			NOT NULL,
    DATA_NASC_MOT		DATE				NOT NULL,
    CPF_MOT 			VARCHAR(14)		    NOT NULL,
    MODELO_CAR_MOT		VARCHAR(50)			NOT	NULL,
    STATUS_MOT			BOOLEAN				NOT NULL		DEFAULT	FALSE,
    SEXO_MOT			CHAR(1)				NOT NULL,
    PRIMARY	KEY	(ID_MOT)
);

--
-- Definition of table TB_PASSAGEIRO
--

DROP TABLE IF EXISTS TB_PASSAGEIRO;
CREATE TABLE TB_PASSAGEIRO(
	ID_PAS				INTEGER			    AUTO_INCREMENT,
    NOME_PAS			VARCHAR(50)			NOT NULL,
    DATA_NASC_PAS		DATE				NOT NULL,
    CPF_PAS 			VARCHAR(14)		    NOT NULL,
    SEXO_PAS			CHAR(1)				NOT NULL,
    PRIMARY	KEY	(ID_PAS)
);

--
-- Definition of table TB_CORRIDA
--

DROP TABLE IF EXISTS TB_CORRIDA;
CREATE TABLE TB_CORRIDA(
	ID_COR				INTEGER			    AUTO_INCREMENT,
    LOCAL_PARTIDA_COR	VARCHAR(50),
    LOCAL_CHEGADA_COR	VARCHAR(50),
    VALOR_COR			DOUBLE(10,2)		NOT NULL,
	ID_PAS_COR			INTEGER				NOT NULL,
	ID_MOT_COR			INTEGER			    NOT NULL,
	CONSTRAINT FK_PAS_COR FOREIGN KEY (ID_PAS_COR) 	REFERENCES TB_PASSAGEIRO (ID_PAS),
	CONSTRAINT FK_MOT_COR FOREIGN KEY (ID_MOT_COR) 	REFERENCES TB_MOTORISTA (ID_MOT),
    PRIMARY	KEY	(ID_COR)
);

--
-- Definition of table TB_USUARIO
--

DROP TABLE IF EXISTS TB_USUARIO;
CREATE TABLE TB_USUARIO(
	ID_USU				INTEGER			    AUTO_INCREMENT,
    NOME_USU			VARCHAR(50)			NOT NULL,
    LOGIN_USU			VARCHAR(20)			NOT NULL,
    SENHA_USU			VARCHAR(30)			NOT NULL,
	IMG_USU				VARCHAR(100),
    PRIMARY	KEY	(ID_USU)
);

--
-- INSERT NAS TABELAS 
--

INSERT INTO TB_PASSAGEIRO(
    NOME_PAS,
    DATA_NASC_PAS,
    CPF_PAS,
    SEXO_PAS
)VALUES(
	'Maria da silva sauro',
    '1994-03-22',
    '454.006.228.02',
    'F'
);

INSERT INTO TB_MOTORISTA(
    NOME_MOT,
    DATA_NASC_MOT,
    CPF_MOT,
    MODELO_CAR_MOT,
    STATUS_MOT,
    SEXO_MOT
)VALUES(
	'João da silva sauro',
    '1994-03-21',
	'454.006.228-01',
	'CORSA',
    TRUE,
    'M'
);